[Main]
Title = "Api gateway service v0.1"
ListenStr = "0.0.0.0:9000"
Release = "0.1"
LogFile="api-gateway.log"

[TokenService]
ListenStr="localhost:8080"
Protocol="http"
IssueTokenPath="/token"
VerifyTokenPath="/token/verify"
RevokeTokenPath="/token/revoke"
