[Main]
Title = "Api gateway service v0.1"
Release = "0.1"
ServiceName="Api Gateway"
LogFile="api-gateway.log"

[TokenService]
ListenStr="localhost:8080"
Protocol="http"
IssueTokenPath="/token"
VerifyTokenPath="/token/verify"
RevokeTokenPath="/token/revoke"
